### ISSUE TITLE
PlayPause key does not work.

### ISSUE THREAD

**Issue by SASDOE** [borismus/keysocket#81] opened 2014-11-19 06:36 UTC
PlayPause key doensn't work with Jamstash (haven't tried any other clients).

Next/Prev do.

Using Chromium 38.0.2125.111, archlinux 3.17.2-1-ARCH

**Comment by ticklemynausea** [comment] 2015-02-02 14:16
This is happening to me with Jamstash too. Key bindings are correctly configured in chrome. Stop and Play/Pause don't work, next and prev do.

**Comment by borismus** [comment] 2015-03-20 23:23
Dupe of https://github.com/borismus/keysocket/issues/109

**Closed by borismus** 2015-03-20 23:23 UTC
