### ISSUE TITLE
jamstash broken

### ISSUE THREAD

**Issue by narcoclepsy** [borismus/keysocket#61] opened 2014-06-13 04:05 UTC
the element ID for the play / pause buttons are no longer in place. If I add an ID manually to the page using the inspector and change the js as so it works

var connection = null;
var isConnected = false;

function controlJamstash(key) {
    if(key === PREV) {
        //var prevButton = document.getElementById('PreviousTrack');
        var prevButton = document.querySelector('#PreviousTrack');
        simulateClick(prevButton);
    } else if(key === NEXT) {
        var nextButton = document.getElementById('NextTrack');
        simulateClick(nextButton);
    } else if(key === PLAY) {
        var isPlaying = document.querySelector('a.button.PlayTrack').style.display === 'none';
        var playPauseButton = null;
        if(isPlaying) {
          playPauseButton = document.getElementById('TheEffingButton');
          //playPauseButton = document.querySelector('a.button.PlayTrack')
        } else {
          playPauseButton = document.querySelector('.PauseTrack')
          //playPauseButton = document.getElementById('PlayTrack');
        }
        simulateClick(playPauseButton);
    }
}

reconnect(controlJamstash, connection, isConnected);

I also tried to adjust this using the querySelector fn to target the buttons by their existing class names something derails there. works by ID, fails by class. I'll dig further but I thought maybe someone might see the issue putting their eyes to this. Also note that the prev/next track buttons (by id with existing ID attributes on the elements) still work.

**Comment by borismus** [comment] 2015-03-20 23:23
Dupe of https://github.com/borismus/keysocket/issues/109

**Closed by borismus** 2015-03-20 23:23 UTC
